language: sh
dist:     trusty
sudo:     false
install:
  - git clone git://github.com/rylnd/shpec --branch  0.2.2 --depth 1 "$HOME"/shpec
  - export PATH=$HOME/shpec/bin:$TRAVIS_BUILD_DIR/lib:$PATH
script:   ./all-shpecs
git:
  depth:  1
