language: sh
dist:     trusty
before_install:
  - wget https://ftp.gnu.org/gnu/bash/bash-4.3.30.tar.gz
  - tar xf bash-4.3.30.tar.gz
  - cd bash-4.3.30
  - ./configure
  - make
  - sudo make install
install:
  - git clone git://github.com/rylnd/shpec --branch  0.2.2 --depth 1 "$HOME"/shpec
  - export PATH=$HOME/shpec/bin:$TRAVIS_BUILD_DIR/lib:$PATH
script:   ./all-shpecs
git:
  depth:  1
